#Author: Alberto Moccardi
# Version: 1.0  
# Date: 2024-07-08
# Deep Learning for predictive maintenance course

# Dockerfile.generator
FROM python:3.9-slim
WORKDIR /app

# Install requirements
COPY Streamlit_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the user generation script
COPY data/generate_users_stream.py .

# Command to execute the Python script
CMD ["python", "generate_users_stream.py"]
